// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multi_id.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FollowerRelation struct {
	Account              *AccountName `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Follower             *AccountName `protobuf:"bytes,2,opt,name=follower,proto3" json:"follower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FollowerRelation) Reset()         { *m = FollowerRelation{} }
func (m *FollowerRelation) String() string { return proto.CompactTextString(m) }
func (*FollowerRelation) ProtoMessage()    {}
func (*FollowerRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{0}
}

func (m *FollowerRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerRelation.Unmarshal(m, b)
}
func (m *FollowerRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerRelation.Marshal(b, m, deterministic)
}
func (m *FollowerRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerRelation.Merge(m, src)
}
func (m *FollowerRelation) XXX_Size() int {
	return xxx_messageInfo_FollowerRelation.Size(m)
}
func (m *FollowerRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerRelation.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerRelation proto.InternalMessageInfo

func (m *FollowerRelation) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FollowerRelation) GetFollower() *AccountName {
	if m != nil {
		return m.Follower
	}
	return nil
}

type FollowingRelation struct {
	Account              *AccountName `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Following            *AccountName `protobuf:"bytes,2,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FollowingRelation) Reset()         { *m = FollowingRelation{} }
func (m *FollowingRelation) String() string { return proto.CompactTextString(m) }
func (*FollowingRelation) ProtoMessage()    {}
func (*FollowingRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{1}
}

func (m *FollowingRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingRelation.Unmarshal(m, b)
}
func (m *FollowingRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingRelation.Marshal(b, m, deterministic)
}
func (m *FollowingRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingRelation.Merge(m, src)
}
func (m *FollowingRelation) XXX_Size() int {
	return xxx_messageInfo_FollowingRelation.Size(m)
}
func (m *FollowingRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingRelation.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingRelation proto.InternalMessageInfo

func (m *FollowingRelation) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FollowingRelation) GetFollowing() *AccountName {
	if m != nil {
		return m.Following
	}
	return nil
}

type FollowerCreatedOrder struct {
	Account              *AccountName  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          *TimePointSec `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Follower             *AccountName  `protobuf:"bytes,3,opt,name=follower,proto3" json:"follower,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FollowerCreatedOrder) Reset()         { *m = FollowerCreatedOrder{} }
func (m *FollowerCreatedOrder) String() string { return proto.CompactTextString(m) }
func (*FollowerCreatedOrder) ProtoMessage()    {}
func (*FollowerCreatedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{2}
}

func (m *FollowerCreatedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerCreatedOrder.Unmarshal(m, b)
}
func (m *FollowerCreatedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerCreatedOrder.Marshal(b, m, deterministic)
}
func (m *FollowerCreatedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerCreatedOrder.Merge(m, src)
}
func (m *FollowerCreatedOrder) XXX_Size() int {
	return xxx_messageInfo_FollowerCreatedOrder.Size(m)
}
func (m *FollowerCreatedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerCreatedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerCreatedOrder proto.InternalMessageInfo

func (m *FollowerCreatedOrder) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FollowerCreatedOrder) GetCreatedTime() *TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *FollowerCreatedOrder) GetFollower() *AccountName {
	if m != nil {
		return m.Follower
	}
	return nil
}

type FollowingCreatedOrder struct {
	Account              *AccountName  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          *TimePointSec `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Following            *AccountName  `protobuf:"bytes,3,opt,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FollowingCreatedOrder) Reset()         { *m = FollowingCreatedOrder{} }
func (m *FollowingCreatedOrder) String() string { return proto.CompactTextString(m) }
func (*FollowingCreatedOrder) ProtoMessage()    {}
func (*FollowingCreatedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{3}
}

func (m *FollowingCreatedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingCreatedOrder.Unmarshal(m, b)
}
func (m *FollowingCreatedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingCreatedOrder.Marshal(b, m, deterministic)
}
func (m *FollowingCreatedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingCreatedOrder.Merge(m, src)
}
func (m *FollowingCreatedOrder) XXX_Size() int {
	return xxx_messageInfo_FollowingCreatedOrder.Size(m)
}
func (m *FollowingCreatedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingCreatedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingCreatedOrder proto.InternalMessageInfo

func (m *FollowingCreatedOrder) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *FollowingCreatedOrder) GetCreatedTime() *TimePointSec {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *FollowingCreatedOrder) GetFollowing() *AccountName {
	if m != nil {
		return m.Following
	}
	return nil
}

type PostCreatedOrder struct {
	Created              *TimePointSec `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	ParentId             uint64        `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostCreatedOrder) Reset()         { *m = PostCreatedOrder{} }
func (m *PostCreatedOrder) String() string { return proto.CompactTextString(m) }
func (*PostCreatedOrder) ProtoMessage()    {}
func (*PostCreatedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{4}
}

func (m *PostCreatedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCreatedOrder.Unmarshal(m, b)
}
func (m *PostCreatedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCreatedOrder.Marshal(b, m, deterministic)
}
func (m *PostCreatedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCreatedOrder.Merge(m, src)
}
func (m *PostCreatedOrder) XXX_Size() int {
	return xxx_messageInfo_PostCreatedOrder.Size(m)
}
func (m *PostCreatedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCreatedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PostCreatedOrder proto.InternalMessageInfo

func (m *PostCreatedOrder) GetCreated() *TimePointSec {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PostCreatedOrder) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type VoterId struct {
	Voter                *AccountName `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	PostId               uint64       `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VoterId) Reset()         { *m = VoterId{} }
func (m *VoterId) String() string { return proto.CompactTextString(m) }
func (*VoterId) ProtoMessage()    {}
func (*VoterId) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{5}
}

func (m *VoterId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoterId.Unmarshal(m, b)
}
func (m *VoterId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoterId.Marshal(b, m, deterministic)
}
func (m *VoterId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoterId.Merge(m, src)
}
func (m *VoterId) XXX_Size() int {
	return xxx_messageInfo_VoterId.Size(m)
}
func (m *VoterId) XXX_DiscardUnknown() {
	xxx_messageInfo_VoterId.DiscardUnknown(m)
}

var xxx_messageInfo_VoterId proto.InternalMessageInfo

func (m *VoterId) GetVoter() *AccountName {
	if m != nil {
		return m.Voter
	}
	return nil
}

func (m *VoterId) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type BpVestId struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	VoteVest             *Vest    `protobuf:"bytes,2,opt,name=vote_vest,json=voteVest,proto3" json:"vote_vest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BpVestId) Reset()         { *m = BpVestId{} }
func (m *BpVestId) String() string { return proto.CompactTextString(m) }
func (*BpVestId) ProtoMessage()    {}
func (*BpVestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{6}
}

func (m *BpVestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BpVestId.Unmarshal(m, b)
}
func (m *BpVestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BpVestId.Marshal(b, m, deterministic)
}
func (m *BpVestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BpVestId.Merge(m, src)
}
func (m *BpVestId) XXX_Size() int {
	return xxx_messageInfo_BpVestId.Size(m)
}
func (m *BpVestId) XXX_DiscardUnknown() {
	xxx_messageInfo_BpVestId.DiscardUnknown(m)
}

var xxx_messageInfo_BpVestId proto.InternalMessageInfo

func (m *BpVestId) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *BpVestId) GetVoteVest() *Vest {
	if m != nil {
		return m.VoteVest
	}
	return nil
}

type BpBlockProducerId struct {
	BlockProducer        *AccountName `protobuf:"bytes,1,opt,name=block_producer,json=blockProducer,proto3" json:"block_producer,omitempty"`
	Voter                *AccountName `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BpBlockProducerId) Reset()         { *m = BpBlockProducerId{} }
func (m *BpBlockProducerId) String() string { return proto.CompactTextString(m) }
func (*BpBlockProducerId) ProtoMessage()    {}
func (*BpBlockProducerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{7}
}

func (m *BpBlockProducerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BpBlockProducerId.Unmarshal(m, b)
}
func (m *BpBlockProducerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BpBlockProducerId.Marshal(b, m, deterministic)
}
func (m *BpBlockProducerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BpBlockProducerId.Merge(m, src)
}
func (m *BpBlockProducerId) XXX_Size() int {
	return xxx_messageInfo_BpBlockProducerId.Size(m)
}
func (m *BpBlockProducerId) XXX_DiscardUnknown() {
	xxx_messageInfo_BpBlockProducerId.DiscardUnknown(m)
}

var xxx_messageInfo_BpBlockProducerId proto.InternalMessageInfo

func (m *BpBlockProducerId) GetBlockProducer() *AccountName {
	if m != nil {
		return m.BlockProducer
	}
	return nil
}

func (m *BpBlockProducerId) GetVoter() *AccountName {
	if m != nil {
		return m.Voter
	}
	return nil
}

type ContractId struct {
	Owner                *AccountName `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Cname                string       `protobuf:"bytes,2,opt,name=cname,proto3" json:"cname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContractId) Reset()         { *m = ContractId{} }
func (m *ContractId) String() string { return proto.CompactTextString(m) }
func (*ContractId) ProtoMessage()    {}
func (*ContractId) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{8}
}

func (m *ContractId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractId.Unmarshal(m, b)
}
func (m *ContractId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractId.Marshal(b, m, deterministic)
}
func (m *ContractId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractId.Merge(m, src)
}
func (m *ContractId) XXX_Size() int {
	return xxx_messageInfo_ContractId.Size(m)
}
func (m *ContractId) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractId.DiscardUnknown(m)
}

var xxx_messageInfo_ContractId proto.InternalMessageInfo

func (m *ContractId) GetOwner() *AccountName {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ContractId) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

type ReplyCreatedOrder struct {
	ParentId             uint64        `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Created              *TimePointSec `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyCreatedOrder) Reset()         { *m = ReplyCreatedOrder{} }
func (m *ReplyCreatedOrder) String() string { return proto.CompactTextString(m) }
func (*ReplyCreatedOrder) ProtoMessage()    {}
func (*ReplyCreatedOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{9}
}

func (m *ReplyCreatedOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCreatedOrder.Unmarshal(m, b)
}
func (m *ReplyCreatedOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCreatedOrder.Marshal(b, m, deterministic)
}
func (m *ReplyCreatedOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCreatedOrder.Merge(m, src)
}
func (m *ReplyCreatedOrder) XXX_Size() int {
	return xxx_messageInfo_ReplyCreatedOrder.Size(m)
}
func (m *ReplyCreatedOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCreatedOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCreatedOrder proto.InternalMessageInfo

func (m *ReplyCreatedOrder) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *ReplyCreatedOrder) GetCreated() *TimePointSec {
	if m != nil {
		return m.Created
	}
	return nil
}

type UserPostCreateOrder struct {
	Author               *AccountName  `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Create               *TimePointSec `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserPostCreateOrder) Reset()         { *m = UserPostCreateOrder{} }
func (m *UserPostCreateOrder) String() string { return proto.CompactTextString(m) }
func (*UserPostCreateOrder) ProtoMessage()    {}
func (*UserPostCreateOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{10}
}

func (m *UserPostCreateOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPostCreateOrder.Unmarshal(m, b)
}
func (m *UserPostCreateOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPostCreateOrder.Marshal(b, m, deterministic)
}
func (m *UserPostCreateOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPostCreateOrder.Merge(m, src)
}
func (m *UserPostCreateOrder) XXX_Size() int {
	return xxx_messageInfo_UserPostCreateOrder.Size(m)
}
func (m *UserPostCreateOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPostCreateOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserPostCreateOrder proto.InternalMessageInfo

func (m *UserPostCreateOrder) GetAuthor() *AccountName {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *UserPostCreateOrder) GetCreate() *TimePointSec {
	if m != nil {
		return m.Create
	}
	return nil
}

type RewardCashoutId struct {
	Account              *AccountName `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PostId               uint64       `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RewardCashoutId) Reset()         { *m = RewardCashoutId{} }
func (m *RewardCashoutId) String() string { return proto.CompactTextString(m) }
func (*RewardCashoutId) ProtoMessage()    {}
func (*RewardCashoutId) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{11}
}

func (m *RewardCashoutId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardCashoutId.Unmarshal(m, b)
}
func (m *RewardCashoutId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardCashoutId.Marshal(b, m, deterministic)
}
func (m *RewardCashoutId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardCashoutId.Merge(m, src)
}
func (m *RewardCashoutId) XXX_Size() int {
	return xxx_messageInfo_RewardCashoutId.Size(m)
}
func (m *RewardCashoutId) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardCashoutId.DiscardUnknown(m)
}

var xxx_messageInfo_RewardCashoutId proto.InternalMessageInfo

func (m *RewardCashoutId) GetAccount() *AccountName {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *RewardCashoutId) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type UserTrxCreateOrder struct {
	Creator              *AccountName  `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime           *TimePointSec `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserTrxCreateOrder) Reset()         { *m = UserTrxCreateOrder{} }
func (m *UserTrxCreateOrder) String() string { return proto.CompactTextString(m) }
func (*UserTrxCreateOrder) ProtoMessage()    {}
func (*UserTrxCreateOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{12}
}

func (m *UserTrxCreateOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTrxCreateOrder.Unmarshal(m, b)
}
func (m *UserTrxCreateOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTrxCreateOrder.Marshal(b, m, deterministic)
}
func (m *UserTrxCreateOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTrxCreateOrder.Merge(m, src)
}
func (m *UserTrxCreateOrder) XXX_Size() int {
	return xxx_messageInfo_UserTrxCreateOrder.Size(m)
}
func (m *UserTrxCreateOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTrxCreateOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserTrxCreateOrder proto.InternalMessageInfo

func (m *UserTrxCreateOrder) GetCreator() *AccountName {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *UserTrxCreateOrder) GetCreateTime() *TimePointSec {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type StakeRecord struct {
	From                 *AccountName `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *AccountName `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StakeRecord) Reset()         { *m = StakeRecord{} }
func (m *StakeRecord) String() string { return proto.CompactTextString(m) }
func (*StakeRecord) ProtoMessage()    {}
func (*StakeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{13}
}

func (m *StakeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeRecord.Unmarshal(m, b)
}
func (m *StakeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeRecord.Marshal(b, m, deterministic)
}
func (m *StakeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeRecord.Merge(m, src)
}
func (m *StakeRecord) XXX_Size() int {
	return xxx_messageInfo_StakeRecord.Size(m)
}
func (m *StakeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_StakeRecord proto.InternalMessageInfo

func (m *StakeRecord) GetFrom() *AccountName {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *StakeRecord) GetTo() *AccountName {
	if m != nil {
		return m.To
	}
	return nil
}

type StakeRecordReverse struct {
	To                   *AccountName `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 *AccountName `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StakeRecordReverse) Reset()         { *m = StakeRecordReverse{} }
func (m *StakeRecordReverse) String() string { return proto.CompactTextString(m) }
func (*StakeRecordReverse) ProtoMessage()    {}
func (*StakeRecordReverse) Descriptor() ([]byte, []int) {
	return fileDescriptor_852360a31ce16498, []int{14}
}

func (m *StakeRecordReverse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeRecordReverse.Unmarshal(m, b)
}
func (m *StakeRecordReverse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeRecordReverse.Marshal(b, m, deterministic)
}
func (m *StakeRecordReverse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeRecordReverse.Merge(m, src)
}
func (m *StakeRecordReverse) XXX_Size() int {
	return xxx_messageInfo_StakeRecordReverse.Size(m)
}
func (m *StakeRecordReverse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeRecordReverse.DiscardUnknown(m)
}

var xxx_messageInfo_StakeRecordReverse proto.InternalMessageInfo

func (m *StakeRecordReverse) GetTo() *AccountName {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *StakeRecordReverse) GetFrom() *AccountName {
	if m != nil {
		return m.From
	}
	return nil
}

func init() {
	proto.RegisterType((*FollowerRelation)(nil), "prototype.follower_relation")
	proto.RegisterType((*FollowingRelation)(nil), "prototype.following_relation")
	proto.RegisterType((*FollowerCreatedOrder)(nil), "prototype.follower_created_order")
	proto.RegisterType((*FollowingCreatedOrder)(nil), "prototype.following_created_order")
	proto.RegisterType((*PostCreatedOrder)(nil), "prototype.post_created_order")
	proto.RegisterType((*VoterId)(nil), "prototype.voter_id")
	proto.RegisterType((*BpVestId)(nil), "prototype.bp_vest_id")
	proto.RegisterType((*BpBlockProducerId)(nil), "prototype.bp_block_producer_id")
	proto.RegisterType((*ContractId)(nil), "prototype.contract_id")
	proto.RegisterType((*ReplyCreatedOrder)(nil), "prototype.reply_created_order")
	proto.RegisterType((*UserPostCreateOrder)(nil), "prototype.user_post_create_order")
	proto.RegisterType((*RewardCashoutId)(nil), "prototype.reward_cashout_id")
	proto.RegisterType((*UserTrxCreateOrder)(nil), "prototype.user_trx_create_order")
	proto.RegisterType((*StakeRecord)(nil), "prototype.stake_record")
	proto.RegisterType((*StakeRecordReverse)(nil), "prototype.stake_record_reverse")
}

func init() { proto.RegisterFile("multi_id.proto", fileDescriptor_852360a31ce16498) }

var fileDescriptor_852360a31ce16498 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x36, 0x1f, 0x93, 0x52, 0xd4, 0x25, 0x24, 0x05, 0x2e, 0x68, 0x2f, 0x20, 0x01,
	0x41, 0x21, 0xe2, 0x82, 0x10, 0x77, 0x6e, 0xc8, 0x42, 0x5c, 0x57, 0x9b, 0xf5, 0xa4, 0xb5, 0xea,
	0x78, 0xad, 0xf5, 0x38, 0xa1, 0x02, 0x71, 0x83, 0x9f, 0x85, 0xc4, 0x3f, 0x43, 0x5e, 0x6f, 0x1c,
	0xbb, 0x12, 0xb5, 0x55, 0x0e, 0xbd, 0x24, 0xde, 0xd9, 0xb7, 0x6f, 0xde, 0xbc, 0x99, 0x81, 0x93,
	0x75, 0x1e, 0x53, 0x24, 0xa2, 0x70, 0x96, 0x1a, 0x4d, 0x9a, 0x0d, 0xed, 0x1f, 0x5d, 0xa5, 0xf8,
	0x18, 0x8a, 0xdf, 0x32, 0xcc, 0xbf, 0xc1, 0xe9, 0x4a, 0xc7, 0xb1, 0xde, 0xa2, 0x11, 0x06, 0x63,
	0x49, 0x91, 0x4e, 0xd8, 0x1c, 0xfa, 0x52, 0x29, 0x9d, 0x27, 0x74, 0xe6, 0x3d, 0xf5, 0x9e, 0x8f,
	0xde, 0x4c, 0x67, 0xd5, 0xeb, 0x99, 0xbb, 0x11, 0x89, 0x5c, 0x63, 0xb0, 0xc3, 0xb1, 0x05, 0x0c,
	0x76, 0x3c, 0x67, 0xfe, 0xcd, 0x6f, 0x2a, 0x20, 0xff, 0x01, 0xac, 0xfc, 0x8e, 0x92, 0xf3, 0xff,
	0xca, 0xfe, 0x16, 0x86, 0x15, 0x51, 0x5b, 0xfa, 0x3d, 0x92, 0xff, 0xf6, 0x60, 0x52, 0x55, 0xaf,
	0x0c, 0x4a, 0xc2, 0x50, 0x68, 0x13, 0xa2, 0xb9, 0x8d, 0x88, 0xf7, 0x70, 0xbc, 0xe3, 0xa0, 0x68,
	0x8d, 0x4e, 0xc7, 0xa3, 0xda, 0xbb, 0x22, 0x2c, 0x52, 0x1d, 0x25, 0x24, 0x32, 0x54, 0xc1, 0xc8,
	0xc1, 0x3f, 0x47, 0x6b, 0x6c, 0x18, 0x78, 0xd0, 0xd5, 0xc0, 0x3f, 0x1e, 0x4c, 0xf7, 0x0e, 0xde,
	0x71, 0x05, 0x8d, 0x26, 0x1c, 0x74, 0x6e, 0xc2, 0x0a, 0x58, 0xaa, 0x33, 0xba, 0xa6, 0x7e, 0x01,
	0x7d, 0x17, 0x70, 0xea, 0x6f, 0x50, 0xb1, 0x43, 0xb2, 0x27, 0x30, 0x4c, 0xa5, 0xc1, 0x84, 0x44,
	0x14, 0x5a, 0xf1, 0x87, 0xc1, 0xa0, 0x0c, 0x7c, 0x0c, 0x79, 0x00, 0x83, 0x8d, 0x26, 0x34, 0x22,
	0x0a, 0xd9, 0x2b, 0x38, 0xb2, 0xdf, 0x6d, 0xce, 0x94, 0x28, 0x36, 0x85, 0xbe, 0x95, 0x58, 0xb1,
	0xf6, 0x8a, 0xa3, 0xe5, 0x84, 0x65, 0x2a, 0x36, 0x68, 0xef, 0xd8, 0x04, 0x7a, 0x52, 0x51, 0xb4,
	0x41, 0x4b, 0x3b, 0x08, 0xdc, 0x89, 0xbd, 0x84, 0x61, 0xc1, 0x63, 0x71, 0xce, 0xd3, 0xfb, 0xb5,
	0x8c, 0x45, 0x38, 0xb0, 0xda, 0xbe, 0x60, 0x46, 0xfc, 0xa7, 0x07, 0xe3, 0x65, 0x2a, 0x96, 0xb1,
	0x56, 0x97, 0x22, 0x35, 0x3a, 0xcc, 0x55, 0x29, 0xfa, 0x03, 0x9c, 0x34, 0x83, 0x6d, 0xea, 0xef,
	0x59, 0xf8, 0x27, 0x87, 0xde, 0x17, 0xed, 0x77, 0x29, 0x9a, 0x07, 0x30, 0x52, 0x3a, 0x21, 0x23,
	0x15, 0x39, 0xcb, 0xf4, 0x36, 0xe9, 0x60, 0x99, 0x45, 0xb1, 0x31, 0x1c, 0xa9, 0xe2, 0x6c, 0x93,
	0x0d, 0x83, 0xf2, 0xc0, 0xcf, 0xe1, 0x81, 0xc1, 0x34, 0xbe, 0xba, 0xd6, 0xec, 0x46, 0xdf, 0xbc,
	0x66, 0xdf, 0xea, 0x93, 0xe0, 0x77, 0x9d, 0x04, 0xfe, 0x1d, 0x26, 0x79, 0x86, 0x46, 0xd4, 0x26,
	0xcb, 0xe5, 0x7a, 0x0d, 0x3d, 0x99, 0xd3, 0x85, 0x6e, 0x2d, 0xc4, 0xc1, 0xd8, 0x1c, 0x7a, 0x25,
	0x41, 0x7b, 0x7a, 0x07, 0xe4, 0x02, 0x4e, 0x0d, 0x6e, 0xa5, 0x09, 0x85, 0x92, 0xd9, 0x85, 0xce,
	0xad, 0x81, 0xb7, 0xd8, 0xc7, 0x7f, 0xce, 0xdd, 0x2f, 0x0f, 0x1e, 0xda, 0xfa, 0xc8, 0x7c, 0x6d,
	0x96, 0x37, 0x77, 0x6e, 0xb5, 0xd7, 0xb7, 0xc3, 0xb1, 0x77, 0xe0, 0xd6, 0xb8, 0xe3, 0xd2, 0x43,
	0x89, 0x2e, 0x76, 0x9e, 0x87, 0x70, 0x9c, 0x91, 0xbc, 0x44, 0x61, 0x50, 0x69, 0x13, 0xb2, 0x17,
	0x70, 0xb8, 0x32, 0x7a, 0xdd, 0x96, 0xdb, 0x82, 0xd8, 0x33, 0xf0, 0x49, 0xb7, 0x4d, 0xa3, 0x4f,
	0x9a, 0xc7, 0x30, 0xae, 0x67, 0x11, 0x06, 0x37, 0x68, 0x32, 0x74, 0x04, 0x5e, 0x2b, 0x41, 0x25,
	0xcb, 0xef, 0x20, 0x6b, 0xd9, 0xb3, 0xb7, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x24,
	0xe1, 0xbb, 0x42, 0x07, 0x00, 0x00,
}
